# Generated by Django 4.2.4 on 2023-11-03 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/plants/%Y/%m/%d/')),
                ('ec', models.CharField(max_length=1000)),
                ('ph', models.CharField(max_length=1000)),
                ('nitrogen', models.CharField(max_length=1000)),
                ('phosphorus', models.CharField(max_length=1000)),
                ('potassium', models.CharField(max_length=1000)),
                ('temperature', models.CharField(max_length=1000)),
                ('ideal_moisture', models.CharField(max_length=1000)),
                ('fertilizer', models.CharField(max_length=1000)),
                ('plant_coefficient', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=200, null=True)),
                ('m_temp', models.FloatField(blank=True, null=True)),
                ('m_moist', models.FloatField(blank=True, null=True)),
                ('m_ec', models.FloatField(blank=True, null=True)),
                ('m_nitrogen', models.FloatField(blank=True, null=True)),
                ('m_phosphorus', models.FloatField(blank=True, null=True)),
                ('m_potassium', models.FloatField(blank=True, null=True)),
                ('m_ph', models.FloatField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='Core.plant')),
            ],
        ),
    ]
