# Generated by Django 4.2.2 on 2023-06-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='TDS',
            new_name='EC',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='tds',
            new_name='ec',
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizer',
            field=models.ManyToManyField(to='Core.fertilizer'),
        ),
        migrations.AddField(
            model_name='plant',
            name='npk',
            field=models.ManyToManyField(to='Core.npk'),
        ),
        migrations.AddField(
            model_name='plant',
            name='ph',
            field=models.ManyToManyField(to='Core.ph'),
        ),
    ]
