# Generated by Django 4.2.4 on 2023-09-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/plants/%Y/%m/%d/'),
        ),
    ]
