# Generated by Django 4.2.4 on 2024-01-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_type',
        ),
    ]
