# Generated by Django 4.2.2 on 2023-07-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='m_ec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='m_moist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='m_npk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='m_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='m_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
