# Generated by Django 4.2.4 on 2023-12-01 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('developed_by', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='core_images/')),
                ('h1', models.ImageField(blank=True, upload_to='core_images/')),
                ('h2', models.ImageField(blank=True, upload_to='core_images/')),
                ('photos', models.ImageField(blank=True, upload_to='core_images/')),
                ('photos2', models.ImageField(blank=True, upload_to='core_images/')),
                ('photos3', models.ImageField(blank=True, upload_to='core_images/')),
                ('photos4', models.ImageField(blank=True, upload_to='core_images/')),
                ('year_started', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('bio', models.TextField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('api_token', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
